### ISSUE TITLE
Create Profiles Controller for routes

### ISSUE THREAD

**Issue by technica-creative** [okidevnet/okidevnet.github.io#6]
Routes for member pages will need to hit a Controller so they can be handled. Create the controller.

**Comment by birosjh** [comment]
I have already created a Profiles controller in my local repository.  I will push it once I have figured out how to incorporate a template engine.  I'm looking at mustache right now.

**Comment by technica-creative** [comment]
Controller not needed for the member pages for now. We can add a new item after we implement Mongoose for the DB. 
Handlebars templating engine was previously added and merged. Partials folder created and setup in code available for implementation into .hbs template pages.
